name: EBAC-MODULO-11

# Comantos de configuração.
on:
  # sempre que tiver um envio para origin ele vai executar estes comandos
  # Gatilhos de execuções, podendo agendar apra um determinado horário
  push:
    branches: [main]
  pull_request:
    branches: [main]

  # Abilitar workflow manualmente
  workflow_dispatch:

# Tarefas do workflow
jobs:
  # Onde quero executar o fluxo de trabalho
  build:
    # Executar em um windows-latest, ubuntu-latest
    runs-on: ubuntu-latest

    # Qual versão do node vai ser utilizada
    strategy:
      matrix:
        node-version: [12.x]

    # Configurações
    # Configuração que instala o node
    steps:
      - name: Setup Node.js
        uses: actions/setup-node@v2.1.2
        with:
          node-version: ${{ matrix.node-version }}
      - uses: actions/checkout@v2
      #comandos necessários para executar a aplicação da mesma forma que no PC
      - run: npm install

      - run: npx cypress run --config video=true --env allure=true --browser chrome --record --key 26303146-a7a4-4226-a249-bf1a12f2fdd8
      # - run: node runner.js
      #Geração do relatório em HTML allure-report
        - name: Allure report V2
          uses: QuintilianoNery/action-allure-report-V2@0.2.0
          with:
            results-dir: allure-results
            report-dir: allure-report

          #Enviar para o git hub pages
        - name: Deploy to GitHub Pages
          uses: JamesIves/github-pages-deploy-action@3.7.1
          with:
            GITHUB_TOKEN: ${{SECRETS.GITHUB_TOKEN}}
            BRANCH: gh-pages
            FOLDER: allure-report